### PR TITLE
fixed bug where readline instances where shared across prompts

### PR DESCRIPTION
**Pull request by AlecAivazis**
Addresses #43. @rv-cpavlick - mind taking this for a spin to verify things are working? I added your example as a new test so we should be able to verify that this won't regress

### CODE REVIEW

**Comment by rv-cpavlick** [comment]
This is what I am seeing when I run your code now: 

survey_bug

**Comment by rv-cpavlick** [comment]
Never mind, my branch didn't actually seem to switch. It looks to be working now.

**Comment by AlecAivazis** [comment]
Awesome! No worries about the false alarm. Mind approving this and i'll merge it in a cut a new release ASAP

**Comment by rv-cpavlick** [comment]
I am away from my computer now and will be for a while. I'm sorry!



Powered by Cricket Wireless


-------- Original message --------

**Comment by AlecAivazis** [comment]
No worries at all, i went ahead and merged/cut a new release

**Comment by rv-cpavlick** [comment]
Awesome, thanks again for the responsiveness

**Pull request merged**
