### PR TITLE
Fix bug when runes with width > 1 in an option with multiple lines

### LINKED ISSUE #444: Rendering error when there are runes with width > 1 in an option with multiple lines
**What operating system and terminal are you using?**
Windows 10; Windows Terminal

**An example that showcases the bug.**
image

**What did you expect to see?**
Render correctly.

**What did you see instead?**
Some content has been rendered repeatedly.

There may be a problem with this function (renderer.go: countLines):
image

### PR DESCRIPTION
**Pull request by VCisHere**
fixes #444

### CODE REVIEW

**Comment by AlecAivazis** [comment]
👋 Thanks for submitting this! Please bear with us while we catch up on a lot of PRs that are piling up. We appreciate your patience

**Comment by AlecAivazis** [comment]
@VCisHere mind giving me some quick instructions to see the bug in the current implementation?

**Comment by VCisHere** [comment]
We can enter "一" until the text is more than one line to see the bug.

**Comment by AlecAivazis** [comment]
Awesome, I saw the bug on the current master branch and confirmed your fix works. Thanks again! I pushed up a test so we can ensure this still works moving forward. Will merge once we get the 👍 from github

**Pull request merged**
