### PR TITLE
[Feature] [#273] Improve select all and select none in multiselect prompt.

### PR DESCRIPTION
**Pull request by chiaretto**
### What I did
Added support to select all items on multi select list pressing key right, and select none pressing key left

### How to verify it
```
go run examples/longmulti.go
```
Press Key **[right]** to select all
Press Key **[left]** to select none

###  Description for the changelog
Add feature select all and select none on multi select list

### Issue Related: 
https://github.com/AlecAivazis/survey/issues/273

### Example
multi-select-all-none

### CODE REVIEW

**Comment by henriquemoraes8** [comment]
This could really help us with our project

**Comment by antonioolf** [comment]
It's really a great feature

**Comment by victor-schumacher** [comment]
Such a nice feature

**Comment by AlecAivazis** [comment]
Hey @chiaretto! Thank you for submitting this.

The feature makes sense, the code looks good, there's a test, AND README CHANGES. What more could I ask for? I'm going to pull this down right now to make sure it works on my windows machine and then we'll merge it in.

**Comment by AlecAivazis** [comment]
Works like a charm! Thanks again :)

**Comment by fabianofernandeszup** [comment]
Thank you. I thank you for the excellent lib. I hope to be able to contribute more in the future.
If you are interested, this is the opensource project that we use your lib. https://ritchiecli.io/

**Pull request merged**
