### PR TITLE
Fork Survey lib and Apply Terminal reader patch

### PR DESCRIPTION
**Pull request by th3coop**

### CODE REVIEW

**Comment by th3coop** [comment]
Did not mean to do that.  Sorry for the noise!  Definitely not trying to merge this upstream.

**Comment by AlecAivazis** [comment]
No problem! If someone finds the time to dig deeper into the issues you were having with the windows version, I'd love to help. You can find me on the gophers slack any time!

**Comment by th3coop** [comment]
@AlecAivazis, i'm going to get back to you in the issue I opened with more details.  Sorry for the delay on that point.  I just need to branch for now then we'll get to a better solution.

**Comment by AlecAivazis** [comment]
Best of luck. I'll leave the issue open - no rush!

**Pull request closed without merging**
