### PR TITLE
[Editor] Improve editor prompt

### PR DESCRIPTION
**Pull request by kamontat**
Add support 'Editor' variable for input custom editor cli

### CODE REVIEW

**Comment by AlecAivazis** [comment]
Hey @kamontat - thanks for submitting this PR. Do you mind adding a test to the [editor](https://github.com/AlecAivazis/survey/blob/master/tests/editor.go) test file that tests with an editor that exists commonly on unix systems?

**Comment by kamontat** [comment]
@AlecAivazis I not sure how to test it.

**Comment by AlecAivazis** [comment]
Hey @kamontat - sorry, i should have been more clear.

Those tests are run manually whenever a PR is submitted to verify the behavior of the library. If you could just add an entry to the test file I linked that sets the editor explicitly to something that I can run on my laptop (a 2015 macbook pro) that would be great!

**Comment by kamontat** [comment]
Currently, I don’t have computer with so that will take a while.

**Pull request merged**
