### PR TITLE
allow to change the editor behavior

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
Add two fields `HideDefault` and `AppendDefaul` to `Editor`.

If `HideDefault` is `true`, the default value is not shown
before the launch of the editor. By default this value is `false`.

If `AppendDefault` is `true`, the default value is written to the temporary
file before the launch of the editor and `Prompt()` returns the empty
string if the contents of the temporary file is empty.
By default this value is `false`.

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
This change refers to [Inquirer.js](https://github.com/SBoudrias/Inquirer.js)'s editor behavior.

In many cases the default value is too long to show to the terminal.
And I hope the default value is written in the temporary file when the text editor launches.

**Comment by AlecAivazis** [comment]
Thanks for the contribution @suzuki-shunsuke! Sorry for not getting back to you sooner. Would you mind adding tests to `tests/editor.go` aswell with examples of using both of those parameters?

**Comment by suzuki-shunsuke** [comment]
Hi @AlecAivazis.

Thank you for reply!
I have added tests to tests/editor.go, but to be honest I don't know the good prompt messages.
If the prompt messages are not good, please tell me to correct them.

Best regards.

**Comment by AlecAivazis** [comment]
@suzuki-shunsuke - Those prompts are fine - they're mostly used in automated tests so their values aren't critical.

Just verified all the behavior one last time. Will merge once travis gives us the 👍.

Thanks again for the contribution!

**Pull request merged**
