### PR TITLE
Add core.IsFieldNotMatch function.

### PR DESCRIPTION
**Pull request by kataras**
Hello @AlecAivazis,

I am pushing this PR in order to check if an error is caused of an unmatched field. There are cases when a map can be ignored (e.g. when you have a Transform which stores a value to a non-string type , take for example a map[string]interface{} from file path(input), as it can't just returned as other type because [input.go#101](https://github.com/AlecAivazis/survey/blob/11174a29b34e682c8045cf066601c6343e8e7c72/input.go#L101) will panic).

```go
import "ithub.com/AlecAivazis/survey/v2"
import "ithub.com/AlecAivazis/survey/v2/core"

// [...]

err := survey.Ask(qs, &v);
if err != nil {
  if name, ok := core.IsFieldNotMatch(err); ok {
    // [...name is the not matched question name]
  }
}
```

Please accept this PR as soon as possible, it 
- **does not change any current behavior**
- **does not extend the public API except `/core`**

Happy Holidays!

### CODE REVIEW

**Comment by AlecAivazis** [comment]
Hey @kataras! Happy holidays to you aswell.

I think this is a fine addition to `survey/core`. Mind adding some tests for the new logic?

**Comment by kataras** [comment]
> Hey @kataras! Happy holidays to you aswell.
> 
> I think this is a fine addition to `survey/core`. Mind adding some tests for the new logic?

There is no change on the logic. Just a typed error instead of a string-based error.

**Comment by AlecAivazis** [comment]
@kataras there is in fact new logic. `func (err errFieldNotMatch) Is(target error)` and the `IsFieldNotMatch` are both new functions and methods. I would like to maintain as good coverage as I can and both of these are very easily testable

**Comment by AlecAivazis** [comment]
@kataras - I'm a bit surprised by your response. I hoped that the responsibility act includes test coverage and actually seeing a PR through

I'm going to merge this but you clearly did not read the contribution guidelines and have little intention of adding tests to cover the new logic. Please understand that i have to maintain your contribution and tests help me do that.

**Pull request merged**
