### PR TITLE
Add option to show/hide cursor when prompting user (#345)

### PR DESCRIPTION
**Pull request by dmartin35**

### CODE REVIEW

**Comment by AlecAivazis** [comment]
Thanks for adding this option! I noticed you kept the default behavior the same which I appreciate. I'll take a look at why the github action is failing but once that goes through i suspect we can get this in

**Comment by dmartin35** [comment]
it seems the test workflow is broken when doing the ***install runner*** step (`go get -v github.com/alecaivazis/run`), due to the following error:
`Error: ../../../go/src/github.com/alecaivazis/run/config.go:119:9: undefined: hcl.Unmarshal`

**Comment by AlecAivazis** [comment]
@dmartin35 - i fixed the issue preventing the CI pipeline from executing. Mind rebasing onto master so we can get this in?

**Comment by dmartin35** [comment]
Yes, I did the rebase, I thinks that's good now. Let me know if you need more. Thanks

**Comment by AlecAivazis** [comment]
Perfect, thanks!

**Review by AlecAivazis — APPROVED** [review]

**Pull request merged**
