### PR TITLE
Fix help message for Select

### LINKED ISSUE #218: "space to select" doesn't apply to survey.Select
`survey.Select` has this `SelectQuestionTemplate` which says:

image

but "space to select" is actually not an option here. I think it's meant to work only for `survey.MultiSelect`. Hitting space here works does "type to filter".

### PR DESCRIPTION
**Pull request by ahmetb**
Fixes #218.

### CODE REVIEW

**Comment by AlecAivazis** [comment]
Ah damn! I noticed that a few days ago, fell down a rabbit hole investigating some tests, and completely forgot. Thanks for this!

Travis should pass once the corresponding tests are updated

**Comment by ahmetb** [comment]
Any ideas if this test failure has something to do with the changed code? Windows passes, Go/Mac failing.

```
$ run tests
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by ahmetb** [comment]
I realized test cases are testing the output, so pushing another commit.

**Comment by AlecAivazis** [comment]
Awesome! Thanks for updating the tests

**Pull request merged**
