### PR TITLE
Fix regression in PR #301.

### LINKED ISSUE #319: New OnInterrupt behavior causes crash on Ctrl-C with default settings
**What operating system and terminal are you using?** irrelevant

**An example that showcases the bug.** `go run examples/inputfilesuggestion.go` & press <kbd>Ctrl-C</kbd>

**What did you expect to see?** "interrupt" being printed and program exits

**What did you see instead?** crash on this line: https://github.com/AlecAivazis/survey/blob/f45c05b5039ca1f9c9c562be232f1c4044e0add0/survey.go#L311-L312

This is a regression in v2.2.5 due to the new OnInterrupt feature #301.

@AlecAivazis Why did a new, poorly argued for, backwards-incompatible feature ship in a patch release? Can we expect more functional changes like this in the v2.2.x line?

Would you consider branching off something like a `release-2.2` branch, reverting #301 there, and backporting to it only bug fixes going forward so that we can be sure that new tags on the v2.2.x patch line do _not_ also bundle new features?

### PR DESCRIPTION
**Pull request by infinitepr0**
Fix #319

### CODE REVIEW

**Comment by infinitepr0** [comment]
Regarding #320, I feel running `t.Parallel()` should be done in each test function, rather than the `RunTest` function. However, if there is a strong reason to NOT do the same, I can fix the issue by wrapping each test in `TestOnInterruptFunc` inside another `t.Run()`.

**Comment by infinitepr0** [comment]
Also, isn't the minor version supposed to be incremented, rather than the patch (I believe you're using semver) ?

**Comment by AlecAivazis** [comment]
I reverted the other PR and published onto the `v2.2.x` branch in order to correct version issue. So at the very least we will need to bring the original changes into this PR. 

That being said, I'm not sure the change makes a lot of sense. Thinking about what @mislav said, i agree that this change is pretty unnecessary given that the caller can just look to see if the returned error is an interrupt? Especially considering that the error is returned either way, i can't really see the weight of an addition to the top-level API being worth it.

I'm inclined to close this PR but I want to give you a change to explain if I am missing something.

**Comment by infinitepr0** [comment]
See https://github.com/AlecAivazis/survey/pull/323#issuecomment-748615810

Also, if top level API's are a problem, I could remove the top level API and leave only the `Question` stuct level API.

**Comment by infinitepr0** [comment]
This PR is being closed in correspondence to https://github.com/AlecAivazis/survey/pull/323#issuecomment-749516182.

**Pull request closed without merging**
