### PR TITLE
Handle CJK input

### LINKED ISSUE #272: CJK(Japanese) letter delete(back space) issue
survey-cjk
I found this issue on https://cli.github.com/ . I can reproduce issue on this library. 😺 

maybe its cause by width character. 
I was hitting backspace key. It seems to cursor back by 1. not 2.

### PR DESCRIPTION
**Pull request by execjosh**
CJK runes are rendered using two cells in the console.  So, look at the rune to decide how many cells to move during rendering.

I am not sure how to test this, though.

This fixes #272.

### CODE REVIEW

**Comment by execjosh** [comment]
So, `main` is redeclared inside some packages (i.e., `v2/{test,exaple}s/`), which is causing `go get -v -t ./...` (executed via `travis_install_go_dependencies 1.12 -v`) to fail.  As far as I can tell, this problem has nothing to with the changes introduced by this pull request.

<details>

```
$ go get -v -t ./...
github.com/AlecAivazis/survey/v2/examples
github.com/AlecAivazis/survey/v2/tests
# github.com/AlecAivazis/survey/v2/tests
tests/confirm.go:41:6: main redeclared in this block
	previous declaration at tests/ask.go:29:6
tests/doubleSelect.go:9:5: simpleQs redeclared in this block
	previous declaration at tests/ask.go:10:5
tests/doubleSelect.go:28:6: main redeclared in this block
	previous declaration at tests/confirm.go:41:6
tests/editor.go:11:5: answer redeclared in this block
	previous declaration at tests/confirm.go:8:5
tests/editor.go:13:5: goodTable redeclared in this block
	previous declaration at tests/confirm.go:10:5
tests/editor.go:57:6: main redeclared in this block
	previous declaration at tests/doubleSelect.go:28:6
tests/help.go:16:5: goodTable redeclared in this block
	previous declaration at tests/editor.go:13:5
tests/help.go:53:6: main redeclared in this block
	previous declaration at tests/editor.go:57:6
tests/input.go:29:6: main redeclared in this block
	previous declaration at tests/help.go:53:6
tests/longSelect.go:5:6: main redeclared in this block
	previous declaration at tests/input.go:29:6
tests/longSelect.go:5:6: too many errors
# github.com/AlecAivazis/survey/v2/examples
examples/longlist.go:32:6: main redeclared in this block
	previous declaration at examples/countrylist.go:265:6
examples/longmulti.go:265:6: main redeclared in this block
	previous declaration at examples/longlist.go:32:6
examples/map.go:10:5: simpleQs redeclared in this block
	previous declaration at examples/longlist.go:10:5
examples/map.go:28:6: main redeclared in this block
	previous declaration at examples/longmulti.go:265:6
examples/simple.go:10:5: simpleQs redeclared in this block
	previous declaration at examples/map.go:10:5
examples/simple.go:29:6: main redeclared in this block
	previous declaration at examples/map.go:28:6
examples/validation.go:30:6: main redeclared in this block
	previous declaration at examples/simple.go:29:6
```

</details>

**Comment by AlecAivazis** [comment]
Ooo this is a much cleaner solution than what I've tried to do to fix this. Nice! 

I fixed the CI issue in the `v1` branch, will port that over now.

**Comment by AlecAivazis** [comment]
hey @execjosh! If you rebase onto the current master, you should pick up the fixes. Thanks for being patient

**Comment by AlecAivazis** [comment]
I think this also addresses an issue that @mritd ran into

**Comment by execjosh** [comment]
@AlecAivazis Great!  Thanks for taking a look 😄  Hmm, looks like I needed to `go mod vendor` it, otherwise the tests won't run with `GOFLAGS='-mod=vendor'`.  Some vendored packages disappeared 🤷‍♂  Let me know if you just want me to add `golang.org/x/text` and not remove the others.

**Comment by execjosh** [comment]
Great!  Glad I was able to help 😄

**Pull request merged**
