### PR TITLE
Add support for ppc64le architecture

### PR DESCRIPTION
**Pull request by mkumatag**
As the title mentioned this PR is to add support for ppc64le architecture

### CODE REVIEW

**Comment by mkumatag** [comment]
@AlecAivazis can you please review and help me getting it merged?

**Comment by mkumatag** [comment]
btw: I see tests are green on ppc64le platform and failed ones are on windows platform not related to the changes I made.

**Comment by mkumatag** [comment]
ping @AlecAivazis

**Comment by MarkusFreitag** [comment]
@mkumatag Alec sad he will be very busy for the next few months. So it might take a some time for your PR to get checked.

**Comment by mkumatag** [comment]
> @mkumatag Alec sad he will be very busy for the next few months. So it might take a some time for your PR to get checked.

Changes are very minimal, shouldn't take more than 20-30mins. Please let me know if you need any help from me to review this PR.

**Comment by mkumatag** [comment]
> @mkumatag Alec sad he will be very busy for the next few months. So it might take a some time for your PR to get checked.

@MarkusFreitag @AlecAivazis This is something which is blocking me to run `openshift-installer` tool on ppc64le platform, it will be great if you can help me merging this PR so that I can update the vendor with this fix.

**Comment by AlecAivazis** [comment]
Hey @mkumatag I appreciate that you are blocked at work but this PR has been open for two days and you pinged me **two hours** after it was opened. I work on this project in my free time and ask that you are respectful of that. I dont have time today or maybe even tomorrow to look at why your build is failing. if you want to take a look, be my guest. Otherwise, you will have to wait.

Luckily, go has very good vendoring support so you aren't really blocked : +1:

**Comment by mkumatag** [comment]
> Hey @mkumatag I appreciate that you are blocked at work but this PR has been open for two days and you pinged me **two hours** after it was opened. I work on this project in my free time and ask that you are respectful of that. I dont have time today or maybe even tomorrow to look at why your build is failing. if you want to take a look, be my guest. Otherwise, you will have to wait.
> 
> Luckily, go has very good vendoring support so you aren't really blocked 👍

I understand your concern and here is the root cause for the failure job on windows node:
`run install-deps` is getting the `github.com/kr/pty` code which is forcefully referring `Getsize()` function which is not implemented for windows in the new home(https://github.com/creack/pty) hence `install-deps` was failing. In this codebase, as we are already vendoring the pty code, so I just removed the `go get` code for this particular package.

**Comment by mkumatag** [comment]
Travis job is green now and passed on all 4 possible combinations(x86, ppc64le, mac, windows)

**Comment by AlecAivazis** [comment]
Instead of commenting it out - why not just delete it from the config?

**Comment by mkumatag** [comment]
> Instead of commenting it out - why not just delete it from the config?

done!

**Comment by AlecAivazis** [comment]
Thanks!

**Pull request merged**
