### PR TITLE
feat: Add Description function to multi select

### PR DESCRIPTION
**Pull request by Konkrad**
Adopting the Description function from select to multi select as proposed in #432

### CODE REVIEW

**Comment by AlecAivazis** [comment]
👋 Thanks for submitting this! Please bear with us while we catch up on a lot of PRs that are piling up. We appreciate your patience

**Review by AlecAivazis — CHANGES_REQUESTED** [review]
Hey @Konkrad I finally got around to taking a look at this PR and I noticed there are no tests - mind adding something to `tests/multiselect.go` that showcases the behavior?

**Comment by Konkrad** [comment]
Hello,
I added some tests. If you have ideas for more, please let me know.

**Comment by AlecAivazis** [comment]
Okay, finally found some time to pull this down and check it out. I'm seeing some weird coloring when I have a description set: 

Screen Shot 2022-09-12 at 12 36 04 AM

**Comment by Konkrad** [comment]
Indeed, thanks, I forgot to reset the color. Fixed it. Is there a way to add a test case for this?

**Comment by AlecAivazis** [comment]
Looks good! I just pushed up a test. Will merge once we get the 👍  from github

**Review by AlecAivazis — APPROVED** [review]

**Pull request merged**
