### PR TITLE
[FIX] Mismatch a marked item on MultiSelect.

### PR DESCRIPTION
**Pull request by gjbae1212**
First off, it is a great library.  I have used this library very well.

The issue that i'm using the MultiSelect is that marked items mismatch when a cursor is moving on paginating items.
I have many items, so i should paginate items.

it seems the MultiSelect should compare an index on an option, not index on for-loop(PageEntries). 

please check this. thanks.

### CODE REVIEW

**Comment by AlecAivazis** [comment]
Thanks for submitting this! Sorry I didn't sooner. Mind adding a test that verifies the behavior?

**Comment by AlecAivazis** [comment]
Travis should now be fixed. Mind rebasing and giving it a shot?

**Comment by gjbae1212** [comment]
Ok. I will add a rebase and a test.

**Comment by gjbae1212** [comment]
@AlecAivazis I have added a rebase and a test. check plz.

**Comment by AlecAivazis** [comment]
Looks good! I verified that without the change, the test fails. Not sure how this got passed us for so long

**Comment by AlecAivazis** [comment]
This is now published in `v2.0.4`. Thanks again for the contribution @gjbae1212!!

**Pull request merged**
