### PR TITLE
fix(input.go): delete answer after validate failure

### LINKED ISSUE #350: after validate failure, answer value not output or clean
**What operating system and terminal are you using?**
macos iterm2 zsh

**An example that showcases the bug.**
```golang
package main

import (
	"errors"
	"fmt"
	"net/url"

	"github.com/AlecAivazis/survey/v2"
)


func main() {
	prompt := &survey.Input{Message: "please input a url"}
	var answer url.URL
	err := survey.AskOne(prompt, &answer,survey.WithValidator(urlValidate))
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(answer)
}

func urlValidate(val interface{}) error {
	urlStr, ok := val.(string)
	if !ok || urlStr == "" {
		return errors.New("please input correct url")
	}
	res, err := url.Parse(urlStr)
	if err != nil || res.Scheme == "" || res.Host == "" || res.Path == "" {
		return errors.New("please input correct url")
	}
	return nil
}

```

**What did you expect to see?**
Untitled
i inputed "aaa", then press Enter, the validate not passed, and the answer output  has cleard, but when i continue to type "bbb", the "aaa" will show, continue press Enter, The answer is once again cleared, but when i input "http", the "aaabbb" will show. I think this is a confused behavior, is my code wrong? i also tested `survey.Required`, it has same behavior.
**What did you see instead?**
after validate failure, old answer should show or clean

### PR DESCRIPTION
**Pull request by zigitn**
Closes #350

### CODE REVIEW

**Comment by AlecAivazis** [comment]
@zigitn - i fixed the issue preventing the CI pipeline from executing. Mind rebasing onto master so we can get this in?

**Comment by zigitn** [comment]
Of course, do I need to submit a new pr?

**Comment by AlecAivazis** [comment]
You should be able to get away with just force-pushing over your existing branch

**Comment by AlecAivazis** [comment]
Thanks for doing that @zigitn! Do you mind adding a test that veriies this behavior?

**Comment by cben** [comment]
@AlecAivazis I didn't find existing tests for `WithValidator` that actually test the input.go logic.  Do you have advice how/where to test this?

**Comment by AlecAivazis** [comment]
@cben - thanks for picking this up. I think the [`Ask` tests](https://github.com/AlecAivazis/survey/blob/c79c4a988cde2621cf87a59265233ed7e9e0b63e/survey_test.go#L309) are a good example to copy

**Comment by AlecAivazis** [comment]
Going to close this as its gone a bit stale

**Pull request closed without merging**
