### PR TITLE
fix(cursor): fix terminal cursor move display

### PR DESCRIPTION
**Pull request by mritd**
fix the problem of moving the cursor display when the terminal inputs non-English characters (such as Chinese, Japanese)

refs AlecAivazis/survey#126

Signed-off-by: mritd <mritd1234@gmail.com>

### CODE REVIEW

**Comment by mritd** [comment]
I fixed the cursor display problem using the https://github.com/mattn/go-runewidth library, 
but I don't know how to write a complete test case to test it... 

I did a lot of testing locally, now it looks good work 😂

**Comment by AlecAivazis** [comment]
Thanks for submitting this @mritd. 

I tried using 👫as an input and got some weird behaviors if I moved around and tried to delete it. I haven't yet taken the time to investigate if this is a problem with the `go-runewidth` or something in here but I thought I would raise it to you.

**Comment by mritd** [comment]
@AlecAivazis Have you encountered a problem with the cursor suddenly appearing on the next line?

**Comment by mritd** [comment]
I found in the test: When pressing the left arrow (move button) and the delete button at the same time, there is a certain probability that the cursor will suddenly appear on the next line.



I was testing the master branch code (not merging this PR); I guess this may be due to a location variable thread is not safe.

**Comment by AlecAivazis** [comment]
@mritd any luck hunting this down? There are a bunch of changes that have been merged recently so you probably want to open a new PR based on the current master

**Pull request closed without merging**
