### PR TITLE
Use rune when delete or filter answer

### PR DESCRIPTION
**Pull request by AielloChan**
When using Unicode in the `string` type answer will cause a problem.

Example:

```bash
> go run examples/simple.go
? What is your name? 小明
```

### CODE REVIEW

**Comment by AlecAivazis** [comment]
Hey @AielloChan! Thanks for submitting this fix, would you mind adding a test that shows the problem is fixed?

**Comment by AielloChan** [comment]
Check if that is ok😬

**Comment by AlecAivazis** [comment]
Okay, I finally found some time to pull this down and give it a shot. Thanks for being patient!

Everything seems to behave correctly on my machine, however since this touches a bunch of prompts, i'd like to get a second pair of eyes on it. Maybe @coryb or @mislav have some spare time?

**Comment by AlecAivazis** [comment]
Hm, I might be missing something but wouldn't this also affect the `Select` prompt?

**Comment by AielloChan** [comment]
> Hm, I might be missing something but wouldn't this also affect the `Select` prompt?

Yes, because prompt filter also need use `Rune` for unicode words.

**Review by mislav — APPROVED** [review]
This looks good to me!

**Comment by AlecAivazis** [comment]
great! thanks for taking a look @mislav

**Pull request merged**
